USE [master]
GO

/****** Object:  Database [Insightly]    Script Date: 12/07/2013 14:00:25 ******/
CREATE DATABASE [Insightly] ON  PRIMARY 
( NAME = N'Insightly', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\Insightly.mdf' , SIZE = 7168KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Insightly_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\Insightly_1.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Insightly] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Insightly].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Insightly] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Insightly] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Insightly] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Insightly] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Insightly] SET ARITHABORT OFF 
GO

ALTER DATABASE [Insightly] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Insightly] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Insightly] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Insightly] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Insightly] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Insightly] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Insightly] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Insightly] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Insightly] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Insightly] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Insightly] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Insightly] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Insightly] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Insightly] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Insightly] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Insightly] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Insightly] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Insightly] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Insightly] SET  READ_WRITE 
GO

ALTER DATABASE [Insightly] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Insightly] SET  MULTI_USER 
GO

ALTER DATABASE [Insightly] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Insightly] SET DB_CHAINING OFF 
GO


